[auth.email]
enable_confirmations = true

[auth.phone]
enable_confirmations = false

[auth.external.google]
enabled = true
client_id = "161290474472-qs9d5i6plbllc4gjcov031oi1fk3uf98.apps.googleusercontent.com"
client_secret = "env(GOOGLE_CLIENT_SECRET)"

