import { serve } from "https://deno.land/std@0.168.0/http/server.ts"
import { createClient } from 'https://esm.sh/@supabase/supabase-js@2'
import { jsPDF } from "https://esm.sh/jspdf@2.5.1"
import * as XLSX from "https://esm.sh/xlsx@0.18.5"
import JSZip from "https://esm.sh/jszip@3.10.1"

const corsHeaders = {
  'Access-Control-Allow-Origin': '*',
  'Access-Control-Allow-Headers': 'authorization, x-client-info, apikey, content-type',
}

serve(async (req) => {
  if (req.method === 'OPTIONS') {
    return new Response('ok', { headers: corsHeaders })
  }

  try {
    const supabaseClient = createClient(
      Deno.env.get('SUPABASE_URL') ?? '',
      Deno.env.get('SUPABASE_SERVICE_ROLE_KEY') ?? ''
    )

    // Verify authentication and admin role
    const authHeader = req.headers.get('Authorization')!
    const token = authHeader.replace('Bearer ', '')
    const { data: { user }, error: userError } = await supabaseClient.auth.getUser(token)

    if (userError || !user) throw new Error('Unauthorized')

    const { data: profile } = await supabaseClient
      .from('profiles')
      .select('role')
      .eq('id', user.id)
      .single()

    if (profile?.role !== 'admin') throw new Error('Forbidden: Admin only')

    const { format, date_range, event_types } = await req.json()

    // Fetch settings
    const { data: settingsData } = await supabaseClient
      .from('platform_settings')
      .select('setting_key, setting_value')
      .in('setting_key', ['compliance_email', 'compliance_org_name'])

    const settings = Object.fromEntries(
      settingsData?.map(s => [s.setting_key, s.setting_value]) || []
    )
    const complianceEmail = settings.compliance_email || 'reports@goldxusdt.com'
    const orgName = settings.compliance_org_name || 'GoldX USDT'

    // Fetch audit logs
    let query = supabaseClient
      .from('admin_audit_logs')
      .select(`
        *,
        admin:admin_id (full_name, email)
      `)
      .order('created_at', { ascending: false })

    if (date_range?.start) query = query.gte('created_at', date_range.start)
    if (date_range?.end) query = query.lte('created_at', date_range.end)
    if (event_types?.length) query = query.in('action', event_types)

    const { data: logs, error: logsError } = await query

    if (logsError) throw logsError

    // Anonymize data for the report
    const reportData = (logs || []).map(log => ({
      'Timestamp': new Date(log.created_at).toLocaleString(),
      'Action': log.action,
      'Target Table': log.target_table,
      'Target ID': log.target_id,
      'Details': JSON.stringify({ old: log.old_value, new: log.new_value })
    }))

    const timestamp = new Date().toLocaleString('en-GB', {
      day: '2-digit',
      month: '2-digit',
      year: 'numeric',
      hour: '2-digit',
      minute: '2-digit',
      hour12: true
    }).toUpperCase()
    
    const docId = `AUDIT-${crypto.randomUUID().slice(0, 8).toUpperCase()}-${Date.now()}`
    let finalFile: Uint8Array
    let contentType: string
    let filename: string

    if (format === 'pdf') {
      const doc = new jsPDF()
      
      // Watermark setup
      const watermarkText = `Exported by: ${complianceEmail}\nOrganization: ${orgName}\nDate & Time: ${timestamp}\nDocument ID: ${docId}`
      
      // Header
      doc.setFontSize(18)
      doc.text(`${orgName} - Security Audit Compliance Report`, 105, 20, { align: 'center' })
      doc.setFontSize(10)
      doc.text(`Document ID: ${docId}`, 105, 28, { align: 'center' })
      
      // Watermark on first page (and others if needed)
      doc.setTextColor(200, 200, 200)
      doc.setFontSize(8)
      doc.text(watermarkText, 10, 10)
      
      // Data table (basic implementation)
      doc.setTextColor(0, 0, 0)
      doc.setFontSize(8)
      let y = 40
      reportData.forEach((row, i) => {
        if (y > 270) {
          doc.addPage()
          y = 20
          // Add watermark to each page
          doc.setTextColor(200, 200, 200)
          doc.text(watermarkText, 10, 10)
          doc.setTextColor(0, 0, 0)
        }
        doc.text(`${row.Timestamp} | ${row.Action} | ${row['Target Table']}`, 10, y)
        y += 10
      })

      // Signature section
      doc.setFontSize(10)
      doc.text('Cryptographically Signed by GoldX USDT Compliance Server', 10, 285)
      doc.text(`Hash: ${await generateHash(JSON.stringify(reportData))}`, 10, 290)

      const pdfArrayBuffer = doc.output('arraybuffer')
      finalFile = new Uint8Array(pdfArrayBuffer)
      contentType = 'application/pdf'
      filename = `audit_report_${Date.now()}.pdf`
    } else {
      // CSV or Excel
      const worksheetData = reportData.map(row => ({
        ...row,
        'Report Generated By': complianceEmail,
        'Organization': orgName
      }))

      const hash = await generateHash(JSON.stringify(worksheetData))
      worksheetData.forEach(row => {
        (row as any)['SHA-256 Hash'] = hash
      })

      const wb = XLSX.utils.book_new()
      const ws = XLSX.utils.json_to_sheet(worksheetData)
      XLSX.utils.book_append_sheet(wb, ws, "Audit Logs")

      const fileData = format === 'csv' 
        ? XLSX.utils.sheet_to_csv(ws)
        : XLSX.write(wb, { type: 'buffer', bookType: 'xlsx' })

      const manifest = {
        file_name: `audit_report_${Date.now()}.${format}`,
        export_timestamp: new Date().toISOString(),
        sha256_hash: hash,
        record_count: reportData.length,
        compliance_email: complianceEmail,
        organization_name: orgName,
        document_id: docId
      }

      const zip = new JSZip()
      zip.file(manifest.file_name, fileData)
      zip.file('manifest.json', JSON.stringify(manifest, null, 2))
      
      finalFile = await zip.generateAsync({ type: 'uint8array' })
      contentType = 'application/zip'
      filename = `audit_report_${Date.now()}.zip`
    }

    // Calculate final file hash for DB
    const finalHash = await generateHash(finalFile)

    // Log the export
    await supabaseClient
      .from('compliance_audit_exports')
      .insert({
        admin_id: user.id,
        export_format: format,
        document_id: docId,
        file_hash: finalHash,
        record_count: reportData.length,
        filters: { date_range, event_types }
      })

    return new Response(finalFile, {
      headers: {
        ...corsHeaders,
        'Content-Type': contentType,
        'Content-Disposition': `attachment; filename="${filename}"`,
        'X-Document-ID': docId,
        'X-File-Hash': finalHash
      }
    })

  } catch (error: any) {
    return new Response(JSON.stringify({ error: error.message }), {
      headers: { ...corsHeaders, 'Content-Type': 'application/json' },
      status: 400,
    })
  }
})

async function generateHash(data: string | Uint8Array) {
  const encoder = new TextEncoder()
  const d = typeof data === 'string' ? encoder.encode(data) : data
  const hashBuffer = await crypto.subtle.digest('SHA-256', d)
  const hashArray = Array.from(new Uint8Array(hashBuffer))
  return hashArray.map(b => b.toString(16).padStart(2, '0')).join('')
}
